export interface Country {
    name: string;
    iso: string;
    code: string;
    flag: string;
}

export const countries: Country[] = [
    // African Countries
    { name: 'Algeria', iso: 'DZ', code: '+213', flag: '🇩🇿' },
    { name: 'Angola', iso: 'AO', code: '+244', flag: '🇦🇴' },
    { name: 'Benin', iso: 'BJ', code: '+229', flag: '🇧🇯' },
    { name: 'Botswana', iso: 'BW', code: '+267', flag: '🇧🇼' },
    { name: 'Burkina Faso', iso: 'BF', code: '+226', flag: '🇧🇫' },
    { name: 'Burundi', iso: 'BI', code: '+257', flag: '🇧🇮' },
    { name: 'Cameroon', iso: 'CM', code: '+237', flag: '🇨🇲' },
    { name: 'Cape Verde', iso: 'CV', code: '+238', flag: '🇨🇻' },
    { name: 'Central African Republic', iso: 'CF', code: '+236', flag: '🇨🇫' },
    { name: 'Chad', iso: 'TD', code: '+235', flag: '🇹🇩' },
    { name: 'Comoros', iso: 'KM', code: '+269', flag: '🇰🇲' },
    { name: 'Congo (DRC)', iso: 'CD', code: '+243', flag: '🇨🇩' },
    { name: 'Congo (Republic)', iso: 'CG', code: '+242', flag: '🇨🇬' },
    { name: 'Djibouti', iso: 'DJ', code: '+253', flag: '🇩🇯' },
    { name: 'Egypt', iso: 'EG', code: '+20', flag: '🇪🇬' },
    { name: 'Equatorial Guinea', iso: 'GQ', code: '+240', flag: '🇬🇶' },
    { name: 'Eritrea', iso: 'ER', code: '+291', flag: '🇪🇷' },
    { name: 'Eswatini', iso: 'SZ', code: '+268', flag: '🇸🇿' },
    { name: 'Ethiopia', iso: 'ET', code: '+251', flag: '🇪🇹' },
    { name: 'Gabon', iso: 'GA', code: '+241', flag: '🇬🇦' },
    { name: 'Gambia', iso: 'GM', code: '+220', flag: '🇬🇲' },
    { name: 'Ghana', iso: 'GH', code: '+233', flag: '🇬🇭' },
    { name: 'Guinea', iso: 'GN', code: '+224', flag: '🇬🇳' },
    { name: 'Guinea-Bissau', iso: 'GW', code: '+245', flag: '🇬🇼' },
    { name: 'Ivory Coast', iso: 'CI', code: '+225', flag: '🇨🇮' },
    { name: 'Kenya', iso: 'KE', code: '+254', flag: '🇰🇪' },
    { name: 'Lesotho', iso: 'LS', code: '+266', flag: '🇱🇸' },
    { name: 'Liberia', iso: 'LR', code: '+231', flag: '🇱🇷' },
    { name: 'Libya', iso: 'LY', code: '+218', flag: '🇱🇾' },
    { name: 'Madagascar', iso: 'MG', code: '+261', flag: '🇲🇬' },
    { name: 'Malawi', iso: 'MW', code: '+265', flag: '🇲🇼' },
    { name: 'Mali', iso: 'ML', code: '+223', flag: '🇲🇱' },
    { name: 'Mauritania', iso: 'MR', code: '+222', flag: '🇲🇷' },
    { name: 'Mauritius', iso: 'MU', code: '+230', flag: '🇲🇺' },
    { name: 'Morocco', iso: 'MA', code: '+212', flag: '🇲🇦' },
    { name: 'Mozambique', iso: 'MZ', code: '+258', flag: '🇲🇿' },
    { name: 'Namibia', iso: 'NA', code: '+264', flag: '🇳🇦' },
    { name: 'Niger', iso: 'NE', code: '+227', flag: '🇳🇪' },
    { name: 'Nigeria', iso: 'NG', code: '+234', flag: '🇳🇬' },
    { name: 'Rwanda', iso: 'RW', code: '+250', flag: '🇷🇼' },
    { name: 'Sao Tome and Principe', iso: 'ST', code: '+239', flag: '🇸🇹' },
    { name: 'Senegal', iso: 'SN', code: '+221', flag: '🇸🇳' },
    { name: 'Seychelles', iso: 'SC', code: '+248', flag: '🇸🇨' },
    { name: 'Sierra Leone', iso: 'SL', code: '+232', flag: '🇸🇱' },
    { name: 'Somalia', iso: 'SO', code: '+252', flag: '🇸🇴' },
    { name: 'South Africa', iso: 'ZA', code: '+27', flag: '🇿🇦' },
    { name: 'South Sudan', iso: 'SS', code: '+211', flag: '🇸🇸' },
    { name: 'Sudan', iso: 'SD', code: '+249', flag: '🇸🇩' },
    { name: 'Tanzania', iso: 'TZ', code: '+255', flag: '🇹🇿' },
    { name: 'Togo', iso: 'TG', code: '+228', flag: '🇹🇬' },
    { name: 'Tunisia', iso: 'TN', code: '+216', flag: '🇹🇳' },
    { name: 'Uganda', iso: 'UG', code: '+256', flag: '🇺🇬' },
    { name: 'Zambia', iso: 'ZM', code: '+260', flag: '🇿🇲' },
    { name: 'Zimbabwe', iso: 'ZW', code: '+263', flag: '🇿🇼' },
    
    // Major Countries
    { name: 'United States', iso: 'US', code: '+1', flag: '🇺🇸' },
    { name: 'United Kingdom', iso: 'GB', code: '+44', flag: '🇬🇧' },
    { name: 'Canada', iso: 'CA', code: '+1', flag: '🇨🇦' },
    { name: 'Australia', iso: 'AU', code: '+61', flag: '🇦🇺' },
    { name: 'Germany', iso: 'DE', code: '+49', flag: '🇩🇪' },
    { name: 'France', iso: 'FR', code: '+33', flag: '🇫🇷' },
    { name: 'Italy', iso: 'IT', code: '+39', flag: '🇮🇹' },
    { name: 'Spain', iso: 'ES', code: '+34', flag: '🇪🇸' },
    { name: 'Netherlands', iso: 'NL', code: '+31', flag: '🇳🇱' },
    { name: 'Belgium', iso: 'BE', code: '+32', flag: '🇧🇪' },
    { name: 'Switzerland', iso: 'CH', code: '+41', flag: '🇨🇭' },
    { name: 'Austria', iso: 'AT', code: '+43', flag: '🇦🇹' },
    { name: 'Sweden', iso: 'SE', code: '+46', flag: '🇸🇪' },
    { name: 'Norway', iso: 'NO', code: '+47', flag: '🇳🇴' },
    { name: 'Denmark', iso: 'DK', code: '+45', flag: '🇩🇰' },
    { name: 'Finland', iso: 'FI', code: '+358', flag: '🇫🇮' },
    { name: 'Ireland', iso: 'IE', code: '+353', flag: '🇮🇪' },
    { name: 'Portugal', iso: 'PT', code: '+351', flag: '🇵🇹' },
    { name: 'Poland', iso: 'PL', code: '+48', flag: '🇵🇱' },
    { name: 'Czech Republic', iso: 'CZ', code: '+420', flag: '🇨🇿' },
    { name: 'Hungary', iso: 'HU', code: '+36', flag: '🇭🇺' },
    { name: 'Romania', iso: 'RO', code: '+40', flag: '🇷🇴' },
    { name: 'Greece', iso: 'GR', code: '+30', flag: '🇬🇷' },
    { name: 'Turkey', iso: 'TR', code: '+90', flag: '🇹🇷' },
    { name: 'Russia', iso: 'RU', code: '+7', flag: '🇷🇺' },
    { name: 'China', iso: 'CN', code: '+86', flag: '🇨🇳' },
    { name: 'Japan', iso: 'JP', code: '+81', flag: '🇯🇵' },
    { name: 'South Korea', iso: 'KR', code: '+82', flag: '🇰🇷' },
    { name: 'India', iso: 'IN', code: '+91', flag: '🇮🇳' },
    { name: 'Pakistan', iso: 'PK', code: '+92', flag: '🇵🇰' },
    { name: 'Bangladesh', iso: 'BD', code: '+880', flag: '🇧🇩' },
    { name: 'Indonesia', iso: 'ID', code: '+62', flag: '🇮🇩' },
    { name: 'Malaysia', iso: 'MY', code: '+60', flag: '🇲🇾' },
    { name: 'Philippines', iso: 'PH', code: '+63', flag: '🇵🇭' },
    { name: 'Singapore', iso: 'SG', code: '+65', flag: '🇸🇬' },
    { name: 'Thailand', iso: 'TH', code: '+66', flag: '🇹🇭' },
    { name: 'Vietnam', iso: 'VN', code: '+84', flag: '🇻🇳' },
    { name: 'Brazil', iso: 'BR', code: '+55', flag: '🇧🇷' },
    { name: 'Argentina', iso: 'AR', code: '+54', flag: '🇦🇷' },
    { name: 'Mexico', iso: 'MX', code: '+52', flag: '🇲🇽' },
    { name: 'Colombia', iso: 'CO', code: '+57', flag: '🇨🇴' },
    { name: 'Peru', iso: 'PE', code: '+51', flag: '🇵🇪' },
    { name: 'Chile', iso: 'CL', code: '+56', flag: '🇨🇱' },
    { name: 'Saudi Arabia', iso: 'SA', code: '+966', flag: '🇸🇦' },
    { name: 'United Arab Emirates', iso: 'AE', code: '+971', flag: '🇦🇪' },
    { name: 'Israel', iso: 'IL', code: '+972', flag: '🇮🇱' },
    { name: 'New Zealand', iso: 'NZ', code: '+64', flag: '🇳🇿' },
];

export const getCountryByCode = (phoneCode: string): Country | undefined => {
    return countries.find(c => c.code === phoneCode);
};

export const getCountryByIso = (iso: string): Country | undefined => {
    return countries.find(c => c.iso.toLowerCase() === iso.toLowerCase());
};

export const defaultCountry: Country = countries.find(c => c.iso === 'US')!;
