-- PDF Generation Audit Trail
-- Tracks all PDFs generated by LLM instructions
-- Links to conversation sessions, teacher identity, and LLM reasoning

CREATE TABLE IF NOT EXISTS pdf_generation_audit (
    document_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    school_id TEXT NOT NULL,
    teacher_id TEXT,
    
    -- PDF metadata
    template_type TEXT NOT NULL CHECK(template_type IN ('registration', 'marks_sheet', 'attendance')),
    file_path TEXT NOT NULL,
    file_name TEXT NOT NULL,
    
    -- LLM instruction reference
    llm_instruction_id TEXT,
    
    -- Data quality tracking
    confidence_level REAL,
    
    -- Timestamps
    generated_at BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- LLM reasoning for audit
    reasoning TEXT,
    
    FOREIGN KEY(session_id) REFERENCES teacher_sessions(session_id) ON DELETE CASCADE,
    FOREIGN KEY(school_id) REFERENCES schools(id),
    FOREIGN KEY(teacher_id) REFERENCES users(id)
);

-- Indexes for fast lookup
CREATE INDEX IF NOT EXISTS idx_pdf_audit_session ON pdf_generation_audit(session_id);
CREATE INDEX IF NOT EXISTS idx_pdf_audit_teacher ON pdf_generation_audit(teacher_id);
CREATE INDEX IF NOT EXISTS idx_pdf_audit_template ON pdf_generation_audit(template_type);
CREATE INDEX IF NOT EXISTS idx_pdf_audit_generated_at ON pdf_generation_audit(generated_at DESC);

-- Conversation Context Storage
-- Persists full conversation context for session recovery/audit
CREATE TABLE IF NOT EXISTS conversation_context (
    session_id TEXT PRIMARY KEY,
    teacher_id TEXT NOT NULL,
    school_id TEXT NOT NULL,
    
    -- Context state
    current_phase TEXT,
    confirmation_status TEXT,
    extracted_data_json TEXT, -- JSON of ExtractedData
    
    -- Timestamps
    conversation_started_at BIGINT NOT NULL,
    last_interaction_at BIGINT NOT NULL,
    
    -- Message count for analytics
    message_count INT DEFAULT 0,
    
    FOREIGN KEY(session_id) REFERENCES teacher_sessions(session_id) ON DELETE CASCADE,
    FOREIGN KEY(teacher_id) REFERENCES users(id),
    FOREIGN KEY(school_id) REFERENCES schools(id)
);

CREATE INDEX IF NOT EXISTS idx_conversation_context_teacher ON conversation_context(teacher_id);
CREATE INDEX IF NOT EXISTS idx_conversation_context_phase ON conversation_context(current_phase);

-- Timestamped Message Log
-- Every message in conversation with full context
CREATE TABLE IF NOT EXISTS conversation_messages (
    message_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    
    -- Message metadata
    timestamp BIGINT NOT NULL,
    message_from TEXT NOT NULL CHECK(message_from IN ('teacher', 'system', 'llm')),
    message_type TEXT NOT NULL CHECK(message_type IN ('text', 'image', 'action')),
    phase TEXT,
    
    -- Content
    content TEXT,
    action_taken TEXT,
    
    FOREIGN KEY(session_id) REFERENCES conversation_context(session_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_conversation_messages_session ON conversation_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_conversation_messages_timestamp ON conversation_messages(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_conversation_messages_from ON conversation_messages(message_from);

-- LLM Instructions Log
-- Track all instructions issued by LLM for audit
CREATE TABLE IF NOT EXISTS llm_instructions_log (
    instruction_id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    
    -- Instruction details
    phase TEXT,
    template_type TEXT NOT NULL CHECK(template_type IN ('registration', 'marks_sheet', 'attendance')),
    next_action_type TEXT NOT NULL,
    
    -- Context
    data_collected TEXT, -- JSON array
    issues_found TEXT, -- JSON array
    confidence_level REAL,
    
    -- Reasoning
    reasoning TEXT,
    alternative_actions TEXT, -- JSON array
    
    -- Message to teacher
    message_text TEXT,
    message_tone TEXT,
    
    -- Timestamps
    issued_at BIGINT NOT NULL,
    response_received_at BIGINT,
    status TEXT DEFAULT 'pending',
    
    FOREIGN KEY(session_id) REFERENCES conversation_context(session_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_llm_instructions_session ON llm_instructions_log(session_id);
CREATE INDEX IF NOT EXISTS idx_llm_instructions_status ON llm_instructions_log(status);
CREATE INDEX IF NOT EXISTS idx_llm_instructions_issued_at ON llm_instructions_log(issued_at DESC);
